language: node_js
branches:
  except:
    - production

env:
  global:
    - PORT=3000

jobs:
  include:
  - name: "Node.js 10.x"
    node_js: 10
  - name: "Node.js 12.x"
    node_js: 12

git:
  quiet: true
