
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

author: Adriane Justine Tan
email: eidoriantan@gmail.com

tagline: A translator bot app built for Messenger
color: "#2b594c"

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap
